=== MobyGIS-srl/mundi/src/config-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://github.com/eoxc/CODE-DE/src/config-schema.json",

    "title": "Configuration",
    "description": "The main configuration object.",
    "type": "object",
    "properties": {
        "settings": {
            "$ref": "#/definitions/settings"
        },
        "baseLayers": {
            "$ref": "#/definitions/layerSet"
        },
        "layers": {
            "$ref": "#/definitions/layerSet"
        },
        "overlayLayers": {
            "$ref": "#/definitions/layerSet"
        }
    },
    "required": ["settings", "baseLayers", "layers", "overlayLayers"],

    "definitions": {
        "settings": {
            "description": "The initial settings object.",
            "properties": {
                "center": {
                    "description": "The inital center of the mapview.",
                    "type": "array",
                    "items": [{
                        "description": "The longitude component of the center point.",
                        "type": "number",
                        "minimum": -180,
                        "maximum": 180
                    }, {
                        "description": "The latitude component of the center point.",
                        "type": "number",
                        "minimum": -90,
                        "maximum": 90
                    }]
                },
                "zoom": {
                    "description": "The inital map zoomlevel.",
                    "type": "number",
                    "items": {
                        "type": "number"
                    }
                },
                "extent": {
                    "description": "The initally visible extent. This setting is mutually exclusive to 'center' and 'zoom'.",
                    "type": "array",
                    "items": [{
                        "description": "The lower longitude component of the extent.",
                        "type": "number",
                        "minimum": -180,
                        "maximum": 180
                    }, {
                        "description": "The lower latitude component of the extent.",
                        "type": "number",
                        "minimum": -90,
                        "maximum": 90
                    }, {
                        "description": "The upper longitude component of the extent.",
                        "type": "number",
                        "minimum": -180,
                        "maximum": 180
                    }, {
                        "description": "The upper latitude component of the extent.",
                        "type": "number",
                        "minimum": -90,
                        "maximum": 90
                    }]
                },
                "timeDomain": {
                    "description": "The overall time domain of the client. No time can be selected outside of this domain.",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "minItems": 2,
                    "maxItems": 2
                },
                "selectedTimeDomain": {
                    "description": "The initially selected time of interest.",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "minItems": 2,
                    "maxItems": 2
                },
                "constrainTimeDomain": {
                    "description": "Whether or not the zoomable area shall be confined to the interval of the 'timeDomain' setting.",
                    "type": "boolean",
                    "default": false
                },
                "displayInterval": {
                    "description": "The maximum allowed interval to display on the time slider as an ISO 8601 period.",
                    "type": "string",
                    "pattern": "^P(?:([0-9]+)Y|)?(?:([0-9]+)M|)?(?:([0-9]+)D|)?T?(?:([0-9]+)H|)?(?:([0-9]+)M|)?(?:([0-9]+)S|)?$",
                    "default": null
                },
                "selectableInterval": {
                    "description": "The maximum allowed interval to select as an ISO 8601 period.",
                    "type": "string",
                    "pattern": "^P(?:([0-9]+)Y|)?(?:([0-9]+)M|)?(?:([0-9]+)D|)?T?(?:([0-9]+)H|)?(?:([0-9]+)M|)?(?:([0-9]+)S|)?$",
                    "default": null
                },
                "maxTooltips": {
                    "description": "The maximum number of individual tooltips, before only the beginning of the list is show and a '+ x more' is appended.",
                    "type": "number",
                    "default": null
                },
                "highlightFillColor": {
                    "description": "The fill color of highlighted footprints/bounding boxes on the map. Any valid CSS color defintion is supported.",
                    "type": "string",
                    "default": "rgba(255, 255, 255, 0.2)"
                },
                "highlightStrokeColor": {
                    "description": "The stroke color of highlighted footprints/bounding boxes on the map. Any valid CSS color defintion is supported.",
                    "type": "string",
                    "default": "#cccccc"
                },
                "leftPanelOpen": {
                    "description": "Whether or not the left panel shall be open on start.",
                    "type": "boolean",
                    "default": false
                },
                "rightPanelOpen": {
                    "description": "Whether or not the right panel shall be open on start.",
                    "type": "boolean",
                    "default": false
                }
            },
            "oneOf": [
                { "required": ["center", "zoom", "timeDomain", "selectedTimeDomain"] },
                { "required": ["extent", "timeDomain", "selectedTimeDomain"] }
            ]

        },
        "layerSet": {
            "type": "array",
            "items": { "$ref": "#/definitions/layer" }
        },
        "layer": {
            "description": "The definition of a single layer.",
            "type": "object",
            "properties": {
                "id": {
                    "description": "The unique identifier of this layer.",
                    "type": "string"
                },
                "displayName": {
                    "description": "The layers name to be presented to the user",
                    "type": "string"
                },
                "displayColor": {
                    "description": "The color to distinguish the layer in the layer-list and the TimeSlider. Must be a valid HTML color definition.",
                    "type": "string"
                },
                "display": {
                    "description": "Structure to describe how the layer is visually presented.",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "The ID used for the protocol to identify the layer.",
                            "type": "string"
                        },
                        "visible": {
                            "description": "Whether the layer shall be visible on start.",
                            "type": "boolean",
                            "default": false
                        },
                        "protocol": {
                            "description": "The protocol used to display the layer.",
                            "type": "string",
                            "enum": ["WMS", "WMTS"]
                        },
                        "urls": {
                            "description": "A list of base-URLs to retrieve tiles",
                            "items": {
                                "type": "string",
                                "format": "uri"
                            }
                        },
                        "url": {
                            "description": "A single base-URL to retrieve tiles",
                            "type": "string",
                            "format": "uri"
                        },
                        "matrixSet": {
                            "description": "The matrix set used to retrieve tiles. Required for WMTS.",
                            "type": "string"
                        },
                        "matrixIdPrefix": {
                            "description": "A prefix to be prepended to the numerical part of the tile matrix ID.",
                            "type": "string"
                        },
                        "matrixIdPostfix": {
                            "description": "A postfix to be appended to the numerical part of the tile matrix ID.",
                            "type": "string"
                        },
                        "format": {
                            "description": "The transfer format used to retrieve tiles. For layers and overlayLayers this should be a format that allows transparency (e.g: PNG).",
                            "type": "string"
                        },
                        "projection": {
                            "description": "The projection identifier in which the tiles will be transferred. E.g: 'EPSG:4326'.",
                            "type": "string"
                        },
                        "style": {
                            "description": "The style in which the tiles will be retrieved.",
                            "type": "string"
                        },
                        "attribution": {
                            "description": "A string to be displayed when the layer is displayed. Can contain HTML for specific formatting.",
                            "type": "string"
                        }
                    },
                    "required": ["id", "protocol", "format", "style"],
                    "//Note": "Either 'url' or 'urls' is required. For WMTS matrixSet is mandatory as-well."
                },
                "search": {
                    "description": "An object to define how the layer can be searched.",
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "The identifier used for search requests. Required for EO-WCS only.",
                            "type": "string"
                        },
                        "protocol": {
                            "description": "The protocol used to search for records",
                            "type": "string",
                            "enum": ["EO-WCS", "OpenSearch"],
                            "//TODO": "This list will also include 'WFS', once it's implemented"
                        },
                        "url": {
                            "description": "The base-URL to send search requests to.",
                            "type": "string",
                            "format": "uri"
                        },
                        "format": {
                            "description": "The format (mime-type) to use for OpenSearch requests.",
                            "type": "string",
                            "default": null
                        },
                        "method": {
                            "description": "The preferred HTTP method to send requests.",
                            "type": "string",
                            "enum": ["GET", "POST"],
                            "default": "GET"
                        },
                        "histogramThreshold": {
                            "description": "The threshold of number of records in the whole visible interval to display the dataset as a histogram instead of individual records. When not specified, the records are always shown.",
                            "type": "number",
                            "default": null
                        },
                        "parameters": {
                            "description": "Mapping the parameter type (such as eo:processingCenter) to a settings object.",
                            "type": "object"
                        }
                    },
                    "required": ["protocol", "url"]
                },
                "download": {
                    "description": "An object to define how records of the layer can be downloaded.",
                    "type": "object",
                    "properties": {
                        "protocol": {
                            "description": "The protocol used to download records.",
                            "type": "string",
                            "enum": ["EO-WCS"],
                            "//TODO": "This list will be extended in the future. Currently, this setting is not used with OpenSearch, as the download information is embedded in the search response."
                        },
                        "url": {
                            "description": "The base-URL to send download requests to.",
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": ["protocol", "url"]
                }
            },
            "required": ["id", "displayName", "display"],
            "//Note": "For searchable layers (not base/overlay layers) the 'displayColor' and 'search' properties are mandatory. When the search protocol is NOT OpenSearch, then the 'download' is also mandatory."
        }
    }
}

=== MobyGIS-srl/mundi/src/config-local.json
{
    "settings": {
        "center": [0, 0],
        "zoom": 3,
        "timeDomain": ["2006-01-01T00:00:00Z", "2016-12-31T00:00:00Z"],
        "selectedTimeDomain": ["2006-01-01T00:00:00Z", "2016-12-31T00:00:00Z"],
        "searchFields": [{
            "displayName": "Cloud Coverage",
            "type": "eo:cloudCover"
        }, {

        }]
    },
    "baseLayers": [{
        "id": "terrain-light",
        "displayName": "Terrain-Light",
        "display": {
            "id": "terrain-light",
            "visible": true,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": "Terrain-Light { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors and <a href='javascript:;' onClick='toggle(terrain_attribution)'>others</a>, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> }"
        }
    }, {
        "id": "terrain",
        "displayName": "Terrain",
        "display": {
            "id": "terrain",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": "Terrain { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors and <a href='javascript:;' onClick='toggle(terrain_attribution)'>others</a>, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> }"
        }
    }, {
        "id": "bluemarble",
        "displayName": "Blue Marble",
        "display": {
            "id": "bluemarble",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": "Blue Marble { &copy; <a href=\"http://nasa.gov\" target=\"_blank\">NASA</a> }"
        }
    }],
    "layers": [{
        "id": "MER_FRS_1P_reduced_RGB",
        "displayName": "MER_FRS_1P_reduced_RGB",
        "displayColor": "red",
        "display": {
            "id": "MER_FRS_1P_reduced_RGB",
            "visible": true,
            "protocol": "WMS",
            "urls": [
                "http://localhost:8001/ows"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": ""
        },
        "search": {
            "id": "MER_FRS_1P_reduced_RGB",
            "protocol": "OpenSearch",
            "url": "http://localhost:8001/opensearch/collections/MER_FRS_1P_reduced_RGB/"
        },
        "download": {
            "protocol": "EO-WCS",
            "url": "http://localhost:8001/ows"
        }
    }],
    "overlayLayers": [{
        "id": "coastline",
        "displayName": "Coastline",
        "display": {
            "id": "coastline",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "style": "default",
            "format": "image/png",
            "attribution": "Overlay { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> and <a href=\"https://github.com/mapserver/basemaps\" target=\"_blank\">MapServer</a> }"
        }
    },
    {
        "id": "overlay",
        "displayName": "Borders and Labels",
        "display": {
            "id": "overlay",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "style": "default",
            "format": "image/png",
            "projection": "EPSG:4326",
            "attribution": "Overlay { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> and <a href=\"https://github.com/mapserver/basemaps\" target=\"_blank\">MapServer</a> }"
        }
    }]
}

=== MobyGIS-srl/mundi/src/config-only-1.json
{
    "settings": {
        "center": [0, 0],
        "zoom": 3,
        "timeDomain": ["2006-01-01T00:00:00Z", "2016-12-31T00:00:00Z"],
        "selectedTimeDomain": ["2009-01-01T00:00:00Z", "2012-12-31T00:00:00Z"]
    },
    "baseLayers": [{
        "id": "terrain-light",
        "displayName": "Terrain-Light",
        "display": {
            "id": "terrain-light",
            "visible": true,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": "Terrain-Light { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors and <a href='javascript:;' onClick='toggle(terrain_attribution)'>others</a>, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> }"
        }
    }, {
        "id": "terrain",
        "displayName": "Terrain",
        "display": {
            "id": "terrain",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": "Terrain { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors and <a href='javascript:;' onClick='toggle(terrain_attribution)'>others</a>, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> }"
        }
    }, {
        "id": "bluemarble",
        "displayName": "Blue Marble",
        "display": {
            "id": "bluemarble",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": "Blue Marble { &copy; <a href=\"http://nasa.gov\" target=\"_blank\">NASA</a> }"
        }
    }],
    "layers": [{
        "id": "MER_FRS_RGB",
        "displayName": "MER_FRS_RGB",
        "displayColor": "red",
        "display": {
            "id": "MER_FRS_RGB",
            "visible": true,
            "protocol": "WMS",
            "urls": [
                "http://ows.eox.at/cite_staging/eoxserver/ows"
            ],
            "matrixSet": "WGS84",
            "format": "image/png",
            "projection": "EPSG:4326",
            "style": "default",
            "attribution": ""
        },
        "search": {
            "id": "MER_FRS_RGB",
            "protocol": "OpenSearch",
            "url": "http://ows.eox.at/cite_staging/eoxserver/opensearch/collections/MER_FRS_RGB/"
        }
    }],
    "overlayLayers": [{
        "id": "coastline",
        "displayName": "Coastline",
        "display": {
            "id": "coastline",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "style": "default",
            "format": "image/png",
            "attribution": "Overlay { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> and <a href=\"https://github.com/mapserver/basemaps\" target=\"_blank\">MapServer</a> }"
        }
    },
    {
        "id": "overlay",
        "displayName": "Borders and Labels",
        "display": {
            "id": "overlay",
            "visible": false,
            "protocol": "WMTS",
            "urls": [
                "http://a.tiles.maps.eox.at/wmts/",
                "http://b.tiles.maps.eox.at/wmts/",
                "http://c.tiles.maps.eox.at/wmts/",
                "http://d.tiles.maps.eox.at/wmts/",
                "http://e.tiles.maps.eox.at/wmts/"
            ],
            "matrixSet": "WGS84",
            "style": "default",
            "format": "image/png",
            "projection": "EPSG:4326",
            "attribution": "Overlay { Data &copy; <a href=\"http://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors, Rendering &copy; <a href=\"http://eox.at\" target=\"_blank\">EOX</a> and <a href=\"https://github.com/mapserver/basemaps\" target=\"_blank\">MapServer</a> }"
        }
    }]
}
